# Replace this with the contents of /etc/nixos/hardware-configuration.nix
# generated by the NixOS installer on the laptop machine.
{ ... }:
{
  imports = [ ];
  fileSystems."/" = {
    device = "/dev/nvme0n1p1";
    fsType = "ext4";
  };
  boot.initrd.availableKernelModules = [ ];
}
