# Replace this with the contents of /etc/nixos/hardware-configuration.nix
# generated by the NixOS installer on the desktop machine.
{ ... }:
{
  imports = [ ];
  fileSystems."/" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };
  boot.initrd.availableKernelModules = [ ];
}
